### ISSUE TITLE
encoding

### ISSUE THREAD

**Issue by jonasnic** [pwitab/sos-access#12]
if there is a æ ø å in for example detector_text it will break with .invalid XML content

locally solved by reading the string to encoding UTF8 then decoding back to Latin1
shown in picture
detector will work
detector_text will not work in this pic

![image](https://user-images.githubusercontent.com/19362689/75772929-2605ca00-5d4d-11ea-9784-8d5f2260a6ca.png)

**Comment by Krolken** [comment]
It is the receiving alarm server that answers with invalid XML in the error response.
The resulting error is as intended.

I am guessing that is due to using on Windows. Could you create a AlarmRequest and dump it with the AlarmRequestSchema to see the difference in the XML output?

You might also be able to force UTF-8 on the file by setting the first line to this:

```
# -*- coding: utf-8 -*-
```

But it should be default UTF-8 in python 3. Maybe your editor is set to not UTF-8.

**Comment by jonasnic** [comment]
aha.

I'm not sure how to create the AlarmRequest and dump it with the AlarmRequestSchema
but very interested.

**Comment by Krolken** [comment]
Just create an instance of each and pass the AlarmRequest to the ´dump´ method on the schema.
It is the same process for all messages. And if you need to load xml from the alarm server you pass it to the schemas `load` method and a AlarmRequest will be returned.

```
from sos_access.schemas import AlarmRequest, AlarmRequestSchema

alarm = AlarmRequest(
        event_code="AL",
        authentication="123456678",
        additional_info={"test": "test", "test2": 1},
        transmitter_code="IK00001",
        transmitter_type="SV001",
        receiver="Test",
    )

schema = AlarmRequestSchema()

out_xml = schema.dump(alarm)
print(out_xml)
```

**Comment by jonasnic** [comment]
agree.
what we are sending seems to have a ok formating.
![image](https://user-images.githubusercontent.com/19362689/76072446-45446780-5f98-11ea-964a-f4314dfd94f3.png)

Can we do the same for checking the response? Cant seem to wrap my head around how to do that

**Comment by Krolken** [comment]
The problem is with the receiving server. It doesn't think you are sending proper XML. 

I did find one thing that could be the cause. The xmltodict library I'm using is setting encoding to UTF-8 in the  xml header, but the whole payload is then iso-8859-1 encoded using encoding "latin-1" to comply with the SOS Access v4. 

I tested to send `Å` to SOS Alarm in Sweden and their server does not mind. But maybe the server implementation you are testing agains actually checks the xml header and tries to parse it according to the header and but since it is encoded in iso-8859-1 there is a problem. 

```
'Å'.encode()
b'\xc3\x85'
'Å'.encode('latin-1')
b'\xc5'
```

So if they assume that `Å` is UTF-8 encoded from the header and it actually is iso-8859-1 encoded it would generate an error.

I have a fix for it. I should fix it so that the XML says it is iso-8859-1 encoded and not UTF-8.

But it would be nice if you could verify if the fix works agains you system or if there are other things we need to fix too. 


1. Make an AlarmRequest and dump it to xml. Change UTF-8 to iso-8859-1
2. Call `client.transmit` with the data. You will also need to pass an AlarmRequestResponseSchema instance to the transmit function, there is one on the client itself.

example:
```python
fixed_xml_data = "<xml  encoding="iso-8859-1"....>"
response = client.transmit(fixed_xml_data, client.alarm_response_schema)
print(response)
client._check_response_status(response)  # 
```

**Comment by jonasnic** [comment]
Yep. you are correct. the xmlheader said utf-8

I did the 
```
schema=AlarmRequestScheme()
outxml=schema.dump(alarm)
client.transmit(outxml,client.alarm_response_schema)
```

and it failed 
then i ran 
```
schema=AlarmRequestScheme()
outxml=schema.dump(alarm)

outxml.replace("UTF-8","iso-8859-1")

client.transmit(outxml,client.alarm_response_schema)

```

and it worked.

![image](https://user-images.githubusercontent.com/19362689/76090812-86e70980-5fbc-11ea-901c-40387170deca.png)
