### ISSUE TITLE
New Authentication Response schema - newauthentication field

### ISSUE THREAD

**Issue by PaulKlein** [pwitab/sos-access#17]
Hi there,
I'm trying to test out the 'new authentication' flow and testing what happens for unsuccessful requests.

In these cases (e.g. incorrect old authentication), I would expect the newauthentication field in the response to be empty/omitted, but when I parse this as a response, it fails the NewAuthResponseSchema validation with an error like:

`marshmallow.exceptions.ValidationError: {'newauthentication': ['Field may not be null.']}`

This seems to be because this schema has the authentication marked as required. Is this correct? Do you have examples of an unsuccessful password change, does this just return the old password or something similar here?

FYI as well, in the documentation at https://sos-access.readthedocs.io/en/latest/sos_access_protocol.html#xml-examples-requestnewauthenticationresponse the sample is incorrect, as it shows the auth field as `authentication` and not `newauthentication`. When parsing the sample, I initially got tripped up as it returns an error like:

`marshmallow.exceptions.ValidationError: {'newauthentication': ['Missing data for required field.'], 'authentication': ['Unknown field.']}`

Thanks very much for your useful library + documentation as well, it's been very helpful in my testing.

**Comment by Krolken** [comment]
Hi.

Are you testing the flow agains a live test server of an alarm operator?

I think that if you request a new password with an incorrect one you should be getting a response with NOT_AUTHORIZED status code, but I am not sure if the new_authentication would be empty or echoing the wrong password.

I never tested it out agains a live server since we were running a virtual alarm collector and I didn't need to change them out.

I'll send a message to SOS Alarm to see if my test transmitter still can be used and see what happens.

You are right about the typo. There is the same typo in the specifications :P . Wanna make a PR to fix it?

**Comment by Krolken** [comment]
So wrong password agains SOS Alarm gives:
```
 <?xml version="1.0" encoding="iso-8859-1"?>
<requestnewauthenticationresponse>
  <status>4</status>
  <info>NOT_AUTHORIZED</info>
  <reference />
  <arrivaltime>2021-08-24 13:19:42.301</arrivaltime>
</requestnewauthenticationresponse>
```

Setting the field as optional should solve the problem.

**Comment by Krolken** [comment]
I fixed it.

Could you pull the branch and check if it solves your problem. #18

**Comment by PaulKlein** [comment]
Hi @Krolken thanks for taking a look at this. I don't have access to a real server yet so I was just testing locally using dummy responses. Thanks for showing a real response from the live server, that is useful to confirm.

I would have been happy to do a PR for this but wanted to confirm the 'real' behaviour first to make sure I was on the right track. Looks like you beat me to it :)

I've tested your fix branch against the example response above and it does parse properly now, so this will solve my problem nicely.

Thanks again for your help and taking a look at this so quickly, much appreciated.

**Comment by Krolken** [comment]
No problem. Good that it works. I'll try and merge and release soon.

What system are you planning to run against? I have run it in production agains SOS Alarm and tested it with Nokas and I know some other people have run against some smaller ones too. Always good to know which systems the library can run agains since it is usually a custom made server for each alarm operator.

**Comment by PaulKlein** [comment]
Ah, that's interesting info, I didn't realise custom server-side was common here. We are actually also planning on doing a custom server, integrating it into the [Patriot](https://www.patriotsystems.com) alarm monitoring software. 

Cheers

**Comment by Krolken** [comment]
Cool. New version on PyPI now.
